// Generated by https://quicktype.io

import axios from "axios"
import { Endpoints } from "../config/endpoints"

export interface ProviderResponse {
  _meta: Meta
  category_tree: CategoryTree[]
  provider: Provider
}

export interface AllProvidersResponse {
  _meta: Meta
  providers: { docs: Provider[] }
}

export interface Meta {
  args: Args
  version: string
}

export interface Args {
  provider_code: string
}

export interface CategoryTree {
  children: Child[]
  code: string
  name: string
}

export interface Child {
  code: string
  name: string
}

export interface Provider {
  code: string
  converted_at: string
  created_at: string
  indexed_at: string
  json_data_commit_ref: string
  name: string
  region: string
  slug: string
  terms_of_use: string
  website: string
}

export async function getProvider(code: string): Promise<Provider> {
  const out = await axios.get<ProviderResponse>(
    Endpoints.DBNomics + `providers/${code}`
  )
  return out.data.provider
}

export async function getAllProviders(): Promise<Provider[]> {
  const allProviders = await axios.get<AllProvidersResponse>(
    Endpoints.DBNomics + "providers"
  )
  return allProviders.data.providers.docs
}
