// Generated by https://quicktype.io

import { Dataset } from "./dataset"
import { Provider } from "./provider"

export interface SeriesResponse {
  _meta: Meta
  dataset: Dataset
  errors: null
  provider: Provider
  series: SeriesMeta
}

export interface Meta {
  args: Args
  version: string
}

export interface Args {
  align_periods: boolean
  dataset_code: string
  // dimensions:    ArgsDimensions;
  facets: boolean
  format: string
  limit: number
  metadata: boolean
  observations: boolean
  offset: number
  provider_code: string
  q: string
  series_code: null
}

export interface SeriesMeta {
  docs: SeriesData[]
  limit: number
  num_found: number
  offset: number
}

export interface Series {
  dataset_code: string
  dataset_name: string
  dimensions: any
  indexed_at: string
  provider_code: string
  series_code: string
  series_name: string
}

export interface SeriesData extends Series {
  period: string[]
  period_start_day: string[]
  value: number[]
}
